### ISSUE TITLE
wireguardctrl has been moved and renamed to wgctrl

### ISSUE THREAD

**Issue by mdlayher** [balboah/wireguard-operator#1]
Hello, I've spotted your project as a user of my wireguardctrl project and wanted to reach out to let you know that the project has been moved to the WireGuard org and the main package has been renamed:

https://godoc.org/golang.zx2c4.com/wireguard/wgctrl

It should be fairly easy to update, but feel free to reach out if you run into any issues. Thanks!

**Comment by balboah** [comment]
Thanks for the heads up and for the project of yours, will update dependencies at a later point

**Comment by balboah** [comment]
@mdlayher are you also planning on moving into their git? Because I would rather see the other way around. Wireguard projects on github for easier collaboration :)

**Comment by mdlayher** [comment]
We made the decision to keep it on GitHub for issues and ease of collaboration with pull requests. I can't speak for the other projects but it was important to me that it remain accessible where most users would likely be.
